name: UVLightmeter
main: net.uvnode.uvlightmeter.UVLightmeter
version: 1.0-snapshot
author: jcornwellshiel
website: uv-node.net

commands:
  lightmeter:
    description: UVLightmeter information and help.
    usage: /lightmeter

permissions:
  uvlightmeter.*:
    description: Gives access to all UVLightmeter commands
    children:
      uvlightmeter.admin: true
      uvlightmeter.craft: true
      uvlightmeter.use: true
  uvlightmeter.admin:
    description: Allows players to administer UVLightmeter settings
    default: op
  uvlightmeter.craft:
    description: Allows players to craft light meters
    default: true
  uvlightmeter.use:
    description: Allows players to use light meters
    default: true
     
      